### ISSUE TITLE
Wytyczanie najkrótszej drogi

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#10]
# Opis

Na bazie mapy 2d musimy wyznaczać trasę po której musi się poruszać łazik

# Zadania

- [ ] implementacja A* 
- [ ] fn wyznaczający  bliższy cel
- [ ] testy na mapie 0 1 z małą ilością przeszkód 

# Co wykorzystuje 

- OPEN3D 
- dataset z kilkoma  ujęciami 
- cv2
- 

# Co blokuje

**Comment by DamianKobylinski** [comment]
![Image](https://github.com/knmlprz/TrailblazerML/assets/20757441/7f8585c3-2cb5-41cf-aa92-5ec25be00aaf)

## Algorytm działa:
- [x] od jakiegokolwiek miejsca na mapie 2d do jakiegokolwiek wektora celu 
- [ ] działa w postaci iteracyjnej

## Do wdrożenia 
Iteracyjny model algorytmu

## Co jest potrzebne
W pełni działająca mapa 2d z chmury punktów

**Comment by Kleczyk** [comment]
- [ ] test na mapie gdzie  większość  jest zerem a nielicznie są gdzieś  przeszkody
