### ISSUE TITLE
setup nvidia jetson

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#24]
# Opis

nvidia jetso nie jest przygotowany do testowania z kamerą 

# Zadania

- [x]  przeinstalowanie systemu
- [x] instalacja zależności 
- [x] instalacja oak 
- [x] test loop

# Jak Może wyglądać rozwiązanie 

trzeba wykoanać zadania 

# Co wykorzystuje 

- Ubuntu
- SDK menager nvidia 
- poetry 
- OAK-D

# Co blokuje

**Comment by Kleczyk** [comment]
@DamianKobylinski  @FWalkowicz @Sygnator  @kubabartecki potwierdźcie że jetson działał i dajemy do done doker będzie w innym issue

**Comment by kubabartecki** [comment]
Jetson ok ok
