### ISSUE TITLE
Dodanie paddingów( po których nie może się poruszać ) do przeszkód  mapa 2d

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#29]
# Opis

jak wiemy mapa ma przeszkody a łazik swoją objętość nie jest punktem więc trzeba dodawać bordery o szerokość łazika do przeszkód 

# Zadania

- [ ] do funkcji #28  dodanie puddingów 

# Jak Może wyglądać rozwiązanie 

tam gdzie jest gradient duży w każdą stronę po np 5 sektorów zablokowane 

# Co wykorzystuje 

idk

# Co blokuje 
#28

**Comment by kosiarn** [comment]
this PR adds pudding

![Image](https://github.com/knmlprz/TrailblazerML/assets/62908964/e8605761-d08d-4d4d-8362-05ad686bf217)
